name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: python3.10

    steps:
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Install dependencies
        run: pip install -r requirements.txt
        
      - name: Lint with Flake8
        run: flake8 easybudget tests
        
      - name: Run unit tests
        run: pytest
        
      - name: Verify type annotations
        run: mypy --ignore-missing-imports easybudget
