name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        working-directory: ./backend
        run: pip install -r requirements.txt
        
      - name: Lint
        working-directory: ./backend
        run: flake8 easybudget tests
        
      - name: Unit tests
        working-directory: ./backend
        run: pytest
        
      - name: Typechecking
        working-directory: ./backend
        run: mypy --ignore-missing-imports easybudget
